### ISSUE TITLE
Unrecognized token 'types': was expecting 'null', 'true', 'false' or NaN

### ISSUE THREAD

**Issue by derenrich** [palantir/conjure-python#69]
## What happened?
When using the the binary in the tgz directly (calling `generate` on a known good conjure file that I took from foundry-core) I get the following error

```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.palantir.conjure.python.cli.ConjurePythonCli$GenerateCommand@525f1e4e): java.lang.RuntimeException: Error parsing definition: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'types': was expecting 'null', 'true', 'false' or NaN
 at [Source: (File); line: 1, column: 7]
	at picocli.CommandLine.execute(CommandLine.java:1051)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1214)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
	at picocli.CommandLine.run(CommandLine.java:1864)
	at picocli.CommandLine.run(CommandLine.java:1794)
	at com.palantir.conjure.python.cli.ConjurePythonCli.main(ConjurePythonCli.java:43)
Caused by: java.lang.RuntimeException: Error parsing definition: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'types': was expecting 'null', 'true', 'false' or NaN
 at [Source: (File); line: 1, column: 7]
	at com.palantir.conjure.python.cli.ConjurePythonCli$GenerateCommand.run(ConjurePythonCli.java:108)
	at picocli.CommandLine.execute(CommandLine.java:1043)
	... 8 more
```

## What did you want to happen?

It should've generated bindings.

**Comment by derenrich** [comment]
oh the generator wants an intermediate representation i see
